#!/usr/bin/env python3
"""
Delete Auto-Generated Tasks
Removes tasks that were auto-generated by the agent enhancement import script.
"""

import sys
sys.path.insert(0, '.')

from app import create_app, db
from app.models.task import Task
from app.models.agent import Agent

def delete_auto_generated_tasks(dry_run=False):
    """Delete tasks that are assigned to agents (auto-generated tasks)"""

    print(f"\n{'='*60}")
    print("🗑️  Deleting Auto-Generated Agent Tasks")
    print(f"{'='*60}\n")

    if dry_run:
        print("🔍 DRY RUN MODE - No changes will be made\n")

    # Find all tasks assigned to agents
    agent_tasks = Task.query.filter(
        Task.assigned_to_agent_id.isnot(None)
    ).all()

    print(f"Found {len(agent_tasks)} tasks assigned to agents\n")

    if not agent_tasks:
        print("✅ No auto-generated tasks to delete")
        return

    # Group by agent for reporting
    tasks_by_agent = {}
    for task in agent_tasks:
        agent_name = task.assigned_to_agent.name if task.assigned_to_agent else "Unknown"
        if agent_name not in tasks_by_agent:
            tasks_by_agent[agent_name] = []
        tasks_by_agent[agent_name].append(task)

    # Show what will be deleted
    for agent_name, tasks in tasks_by_agent.items():
        print(f"  {agent_name}: {len(tasks)} tasks")
        if dry_run:
            for task in tasks[:3]:  # Show first 3 as examples
                print(f"    - [{task.priority}] {task.title}")
            if len(tasks) > 3:
                print(f"    ... and {len(tasks) - 3} more")

    print()

    if not dry_run:
        # Delete all agent tasks
        try:
            for task in agent_tasks:
                db.session.delete(task)

            db.session.commit()
            print(f"✅ Successfully deleted {len(agent_tasks)} auto-generated tasks")
        except Exception as e:
            print(f"❌ Error deleting tasks: {e}")
            db.session.rollback()
    else:
        print(f"💡 Run without --dry-run to delete these {len(agent_tasks)} tasks")

    print()


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Delete auto-generated agent tasks')
    parser.add_argument('--dry-run', action='store_true',
                      help='Show what would be deleted without making changes')

    args = parser.parse_args()

    # Create Flask app context
    app = create_app()

    with app.app_context():
        delete_auto_generated_tasks(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
