"""
Update all agent system prompts to include information about available tools
"""
import os
os.environ['DATABASE_URL'] = os.getenv('DATABASE_URL', '')

from app import create_app, db
from app.models.agent import Agent

app = create_app()

with app.app_context():
    # Standard tools section to add to all agents
    tools_section = """

**AVAILABLE TOOLS:**
You have access to the following capabilities through specialized tools:

1. **File Generation Tools** - Create professional documents:
   - generate_pdf_report: Generate formatted PDF reports with tables, headings, and content
   - export_to_csv: Export tabular data to CSV files
   - create_spreadsheet: Create Excel spreadsheets with multiple sheets

2. **File Query Tools** - Search and view generated files:
   - query_files_workspace: Search all files in the workspace by type or name
   - query_files_by_user: View files requested by specific users
   - query_files_by_agent: View files generated by specific agents

3. **Cross-Applet Data Access** - Query data from other departments (READ-ONLY):
   - CRM: query_crm_companies, query_crm_contacts, query_crm_deals, query_crm_deal_details
   - HR: query_hr_employees, query_hr_candidates, query_hr_employee_record, query_hr_pto_calendar, query_hr_pto_balance
   - Support: query_support_tickets, query_support_ticket_details, query_support_metrics
   - Projects: query_project_tasks, query_projects

When users ask questions about files, CRM data, employee information, support tickets, or projects, use these query tools to provide accurate, up-to-date information. You can search, filter, and retrieve data to answer their questions comprehensively.
"""

    # Get all agents
    agents = Agent.query.all()
    print(f"Found {len(agents)} agents to update")

    updated_count = 0
    for agent in agents:
        # Check if the prompt already has the tools section
        if agent.system_prompt and "AVAILABLE TOOLS:" not in agent.system_prompt:
            # Add the tools section to the existing prompt
            agent.system_prompt = agent.system_prompt.strip() + tools_section
            updated_count += 1
            print(f"Updated agent: {agent.name} (ID: {agent.id})")

    # Commit changes
    if updated_count > 0:
        db.session.commit()
        print(f"\n✓ Successfully updated {updated_count} agent prompts")
    else:
        print("\n✓ All agents already have the tools section")
