"""add_business_intelligence_fields_to_tenant

Revision ID: 110c038fc911
Revises: 64c945f85d7c
Create Date: 2025-11-06 13:04:19.382213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110c038fc911'
down_revision = '64c945f85d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_context', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('context_scraped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('context_scraping_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('context_scraping_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('context_scraping_error')
        batch_op.drop_column('context_scraping_status')
        batch_op.drop_column('context_scraped_at')
        batch_op.drop_column('business_context')
        batch_op.drop_column('company_size')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
