"""Add similar lead discovery feature

Revision ID: 183f022448e3
Revises: 855ced990998
Create Date: 2025-12-15 09:01:08.004927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183f022448e3'
down_revision = '855ced990998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_lead_discoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reference_company_id', sa.Integer(), nullable=False),
    sa.Column('reference_company_name', sa.String(length=255), nullable=True),
    sa.Column('similarity_criteria', sa.Text(), nullable=True),
    sa.Column('search_strategy', sa.Text(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('discovered_count', sa.Integer(), nullable=True),
    sa.Column('leads_created', sa.Integer(), nullable=True),
    sa.Column('discovery_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('discovered_companies', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.String(length=20), nullable=True),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('initiated_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reference_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('similar_lead_discoveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_similar_lead_discoveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_similar_lead_discoveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_similar_lead_discoveries_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_similar_lead_discovery', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_to_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('similarity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('similarity_rationale', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('discovery_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['similar_to_company_id'], ['id'])
        batch_op.create_foreign_key(None, 'similar_lead_discoveries', ['discovery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discovery_id')
        batch_op.drop_column('similarity_rationale')
        batch_op.drop_column('similarity_score')
        batch_op.drop_column('similar_to_company_id')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('enable_similar_lead_discovery')

    with op.batch_alter_table('similar_lead_discoveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_similar_lead_discoveries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_similar_lead_discoveries_status'))
        batch_op.drop_index(batch_op.f('ix_similar_lead_discoveries_created_at'))

    op.drop_table('similar_lead_discoveries')
    # ### end Alembic commands ###
