"""add_department_memberships_and_access_control

Revision ID: 25683b830aa6
Revises: 4bffb1d7a520
Create Date: 2025-11-19 09:09:45.259885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25683b830aa6'
down_revision = '4bffb1d7a520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'user_id', name='uq_dept_user_membership')
    )
    with op.batch_alter_table('department_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_department_memberships_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_department_memberships_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_control', sa.String(length=20), nullable=False, server_default='all'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('access_control')

    with op.batch_alter_table('department_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_department_memberships_user_id')
        batch_op.drop_index('ix_department_memberships_department_id')

    op.drop_table('department_memberships')
    # ### end Alembic commands ###
