"""Add title field to users

Revision ID: 28af6949a0fa
Revises: ebc57a8c869a
Create Date: 2025-11-14 11:44:16.086265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28af6949a0fa'
down_revision = 'ebc57a8c869a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add title column to users table
    op.add_column('users', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove title column from users table
    op.drop_column('users', 'title')
    # ### end Alembic commands ###
