"""Add assigned_to_agent_id to tasks

Revision ID: 4376a4e51238
Revises: 0f413411a04d
Create Date: 2025-11-06 13:43:31.299171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4376a4e51238'
down_revision = '0f413411a04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'agents', ['assigned_to_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_agent_id')

    # ### end Alembic commands ###
