"""Add compensation_changes table for HR compensation planning

Revision ID: 469c29c41f90
Revises: f7150578d0b5
Create Date: 2026-01-21 10:27:17.804768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469c29c41f90'
down_revision = 'f7150578d0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compensation_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('previous_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('previous_salary_currency', sa.String(length=3), nullable=True),
    sa.Column('new_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_salary_currency', sa.String(length=3), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus_currency', sa.String(length=3), nullable=True),
    sa.Column('bonus_type', sa.String(length=50), nullable=True),
    sa.Column('raise_percentage', sa.Float(), nullable=True),
    sa.Column('raise_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compensation_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compensation_changes_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensation_changes_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensation_changes_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensation_changes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensation_changes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compensation_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compensation_changes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_compensation_changes_status'))
        batch_op.drop_index(batch_op.f('ix_compensation_changes_employee_id'))
        batch_op.drop_index(batch_op.f('ix_compensation_changes_effective_date'))
        batch_op.drop_index(batch_op.f('ix_compensation_changes_change_type'))

    op.drop_table('compensation_changes')
    # ### end Alembic commands ###
