"""Add agent access control fields

Revision ID: 4bffb1d7a520
Revises: 97fcec5963b5
Create Date: 2025-11-18 23:38:21.063971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bffb1d7a520'
down_revision = '97fcec5963b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_control', sa.String(length=20), nullable=False, server_default='all'))
        batch_op.add_column(sa.Column('allowed_roles', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allowed_department_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allowed_user_ids', sa.Text(), nullable=True))

    with op.batch_alter_table('company_enrichment_cache', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_domain'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_enrichment_cache', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_domain'), ['domain'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('allowed_user_ids')
        batch_op.drop_column('allowed_department_ids')
        batch_op.drop_column('allowed_roles')
        batch_op.drop_column('access_control')

    # ### end Alembic commands ###
