"""add_long_running_task_fields

Revision ID: 4cd00bb095e0
Revises: b2c4d5e6f7g8
Create Date: 2025-11-25 13:20:33.370925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd00bb095e0'
down_revision = 'b2c4d5e6f7g8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_invitations_email'))
        batch_op.drop_index(batch_op.f('idx_invitations_token'))
        batch_op.drop_constraint(batch_op.f('invitations_token_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_messages_agent_created'))
        batch_op.drop_index(batch_op.f('idx_messages_channel_created'))
        batch_op.drop_index(batch_op.f('idx_messages_recipient_created'))
        batch_op.drop_index(batch_op.f('idx_messages_sender_created'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_long_running', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('execution_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('execution_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rq_job_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('queue_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('estimated_completion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_progress_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('execution_result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('execution_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_rq_job_id'), ['rq_job_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_rq_job_id'))
        batch_op.drop_column('retry_count')
        batch_op.drop_column('execution_error')
        batch_op.drop_column('execution_result')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('requires_approval')
        batch_op.drop_column('last_progress_update')
        batch_op.drop_column('estimated_completion')
        batch_op.drop_column('current_step')
        batch_op.drop_column('progress_percentage')
        batch_op.drop_column('queue_name')
        batch_op.drop_column('rq_job_id')
        batch_op.drop_column('execution_model')
        batch_op.drop_column('execution_plan')
        batch_op.drop_column('is_long_running')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_messages_sender_created'), ['sender_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_recipient_created'), ['recipient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_channel_created'), ['channel_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_agent_created'), ['agent_id', 'created_at'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))
        batch_op.create_unique_constraint(batch_op.f('invitations_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_invitations_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_invitations_email'), ['email'], unique=False)

    # ### end Alembic commands ###
