"""Add competitive analysis models and enable_competitive_analysis flag

Revision ID: 5db07fe39c86
Revises: f2924eddc4db
Create Date: 2025-12-08 11:29:10.257931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db07fe39c86'
down_revision = 'f2924eddc4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('suggested_by_agent', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_profiles_website_id'), ['website_id'], unique=False)

    op.create_table('competitive_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('competitor_ids', sa.JSON(), nullable=True),
    sa.Column('competitor_count', sa.Integer(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('comparison_matrix', sa.JSON(), nullable=True),
    sa.Column('detailed_findings', sa.JSON(), nullable=True),
    sa.Column('analyzed_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitive_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitive_analyses_website_id'), ['website_id'], unique=False)

    # Add enable_competitive_analysis column with default value for existing rows
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_competitive_analysis', sa.Boolean(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE agents SET enable_competitive_analysis = FALSE WHERE enable_competitive_analysis IS NULL")

    # Make column non-nullable
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('enable_competitive_analysis', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('enable_competitive_analysis')

    with op.batch_alter_table('competitive_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitive_analyses_website_id'))

    op.drop_table('competitive_analyses')
    with op.batch_alter_table('competitor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_profiles_website_id'))

    op.drop_table('competitor_profiles')
    # ### end Alembic commands ###
