"""Add employee auto-sync and KPI bonus system

Revision ID: 668cbd0cdfac
Revises: 469c29c41f90
Create Date: 2026-01-21 11:59:08.169208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668cbd0cdfac'
down_revision = '469c29c41f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('rule_config', sa.Text(), nullable=False),
    sa.Column('bonus_type', sa.String(length=50), nullable=False),
    sa.Column('use_employee_target_percentage', sa.Boolean(), nullable=False),
    sa.Column('fixed_bonus_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eligible_departments', sa.Text(), nullable=True),
    sa.Column('eligible_roles', sa.Text(), nullable=True),
    sa.Column('minimum_tenure_days', sa.Integer(), nullable=True),
    sa.Column('applies_to_all_employees', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonus_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bonus_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonus_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('monthly_financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('bonus_calculation_triggered', sa.Boolean(), nullable=False),
    sa.Column('quickbooks_synced_at', sa.DateTime(), nullable=True),
    sa.Column('manual_entry_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manual_entry_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year', 'month', name='unique_tenant_month_metrics')
    )
    with op.batch_alter_table('monthly_financial_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_financial_metrics_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_financial_metrics_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_financial_metrics_year'), ['year'], unique=False)

    op.create_table('bonus_calculation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('financial_metrics_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rules_evaluated', sa.Integer(), nullable=True),
    sa.Column('rules_passed', sa.Integer(), nullable=True),
    sa.Column('employees_eligible', sa.Integer(), nullable=True),
    sa.Column('bonuses_created', sa.Integer(), nullable=True),
    sa.Column('total_bonus_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('calculation_details', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['financial_metrics_id'], ['monthly_financial_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonus_calculation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bonus_calculation_logs_calculation_date'), ['calculation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonus_calculation_logs_financial_metrics_id'), ['financial_metrics_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonus_calculation_logs_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('compensation_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kpi_rule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calculation_log_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('financial_metrics_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'monthly_financial_metrics', ['financial_metrics_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'bonus_calculation_logs', ['calculation_log_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'bonus_rules', ['kpi_rule_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compensation_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('financial_metrics_id')
        batch_op.drop_column('calculation_log_id')
        batch_op.drop_column('kpi_rule_id')

    with op.batch_alter_table('bonus_calculation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonus_calculation_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bonus_calculation_logs_financial_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_bonus_calculation_logs_calculation_date'))

    op.drop_table('bonus_calculation_logs')
    with op.batch_alter_table('monthly_financial_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_financial_metrics_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_financial_metrics_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_financial_metrics_month'))

    op.drop_table('monthly_financial_metrics')
    with op.batch_alter_table('bonus_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonus_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bonus_rules_is_active'))

    op.drop_table('bonus_rules')
    # ### end Alembic commands ###
