"""add_timezone_preference_to_users

Revision ID: 67b82a672607
Revises: 79326c217553
Create Date: 2025-12-01 16:30:31.889737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b82a672607'
down_revision = '79326c217553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone_preference', sa.String(length=50), nullable=False, server_default='UTC'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone_preference')

    # ### end Alembic commands ###
