"""Add website builder models (Website, WebsitePage, WebsiteTheme, WebsiteForm, FormSubmission) and agent enable_website_builder permission

Revision ID: 7a7f61e75bae
Revises: 28af6949a0fa
Create Date: 2025-11-17 09:55:01.157038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a7f61e75bae'
down_revision = '28af6949a0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('domain_verified', sa.Boolean(), nullable=False),
    sa.Column('domain_verification_token', sa.String(length=100), nullable=True),
    sa.Column('domain_verified_at', sa.DateTime(), nullable=True),
    sa.Column('default_og_image', sa.String(length=500), nullable=True),
    sa.Column('google_analytics_property_id', sa.String(length=50), nullable=True),
    sa.Column('google_site_verification', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_websites_custom_domain'), ['custom_domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_websites_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('website_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('form_key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('success_message', sa.Text(), nullable=True),
    sa.Column('notification_emails', sa.String(length=500), nullable=True),
    sa.Column('send_confirmation_email', sa.Boolean(), nullable=True),
    sa.Column('confirmation_email_subject', sa.String(length=200), nullable=True),
    sa.Column('confirmation_email_body', sa.Text(), nullable=True),
    sa.Column('create_lead', sa.Boolean(), nullable=False),
    sa.Column('create_contact', sa.Boolean(), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('require_captcha', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_forms_form_key'), ['form_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_website_forms_website_id'), ['website_id'], unique=False)

    op.create_table('website_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('text_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('heading_font', sa.String(length=100), nullable=True),
    sa.Column('body_font', sa.String(length=100), nullable=True),
    sa.Column('header_style', sa.String(length=50), nullable=True),
    sa.Column('footer_style', sa.String(length=50), nullable=True),
    sa.Column('button_style', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_themes_website_id'), ['website_id'], unique=True)

    op.create_table('website_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'slug', name='unique_page_slug_per_website')
    )
    with op.batch_alter_table('website_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_pages_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_pages_website_id'), ['website_id'], unique=False)

    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['website_forms.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_form_id'), ['form_id'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_invitations_email'))
        batch_op.drop_index(batch_op.f('idx_invitations_token'))

    op.drop_table('invitations')
    with op.batch_alter_table('read_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_receipts_message_id'))
        batch_op.drop_index(batch_op.f('ix_read_receipts_user_id'))

    op.drop_table('read_receipts')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_website_builder', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('channel_agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('channel_agents_channel_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('channel_agents_agent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'channels', ['channel_id'], ['id'])
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'])

    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('channel_members_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('channel_members_channel_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'channels', ['channel_id'], ['id'])

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_tenant_id'))
        batch_op.drop_constraint(batch_op.f('uq_tenant_owner_integration_type'), type_='unique')

    with op.batch_alter_table('workspace_applets', schema=None) as batch_op:
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_constraint(batch_op.f('workspace_applets_tenant_id_applet_key_key'), type_='unique')
        batch_op.create_unique_constraint('uq_tenant_applet', ['tenant_id', 'applet_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_applets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenant_applet', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('workspace_applets_tenant_id_applet_key_key'), ['tenant_id', 'applet_key'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tenant_owner_integration_type'), ['tenant_id', 'owner_type', 'owner_id', 'integration_type'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_integrations_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('channel_members_channel_id_fkey'), 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('channel_members_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('channel_agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('channel_agents_agent_id_fkey'), 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('channel_agents_channel_id_fkey'), 'channels', ['channel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('enable_website_builder')

    op.create_table('read_receipts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('read_receipts_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('read_receipts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('read_receipts_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name=op.f('unique_message_user_read'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('read_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_receipts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_read_receipts_message_id'), ['message_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('invitations_invited_by_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('invitations_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey')),
    sa.UniqueConstraint('token', name=op.f('invitations_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_invitations_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_invitations_email'), ['email'], unique=False)

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submissions_form_id'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_created_at'))

    op.drop_table('form_submissions')
    with op.batch_alter_table('website_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_pages_website_id'))
        batch_op.drop_index(batch_op.f('ix_website_pages_slug'))

    op.drop_table('website_pages')
    with op.batch_alter_table('website_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_themes_website_id'))

    op.drop_table('website_themes')
    with op.batch_alter_table('website_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_forms_website_id'))
        batch_op.drop_index(batch_op.f('ix_website_forms_form_key'))

    op.drop_table('website_forms')
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websites_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_websites_custom_domain'))

    op.drop_table('websites')
    # ### end Alembic commands ###
