"""Add status page models

Revision ID: 7e86fc7f44d2
Revises: 668cbd0cdfac
Create Date: 2026-01-22 11:46:43.946825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e86fc7f44d2'
down_revision = '668cbd0cdfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_page_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('page_title', sa.String(length=200), nullable=True),
    sa.Column('page_description', sa.Text(), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('show_incident_history_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_page_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_page_configs_website_id'), ['website_id'], unique=True)

    op.create_table('status_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['status_page_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_components_config_id'), ['config_id'], unique=False)

    op.create_table('status_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('affected_component_ids', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['status_page_configs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_incidents', schema=None) as batch_op:
        batch_op.create_index('idx_config_created', ['config_id', 'created_at'], unique=False)
        batch_op.create_index('idx_config_status', ['config_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_incidents_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_incidents_created_at'), ['created_at'], unique=False)

    op.create_table('status_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=100), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['status_page_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'email', name='unique_subscriber_per_config')
    )
    with op.batch_alter_table('status_subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_subscribers_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_subscribers_confirmation_token'), ['confirmation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_status_subscribers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_subscribers_unsubscribe_token'), ['unsubscribe_token'], unique=True)

    op.create_table('incident_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('notify_subscribers', sa.Boolean(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['status_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_updates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_updates_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_updates_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_updates_created_at'))

    op.drop_table('incident_updates')
    with op.batch_alter_table('status_subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_subscribers_unsubscribe_token'))
        batch_op.drop_index(batch_op.f('ix_status_subscribers_email'))
        batch_op.drop_index(batch_op.f('ix_status_subscribers_confirmation_token'))
        batch_op.drop_index(batch_op.f('ix_status_subscribers_config_id'))

    op.drop_table('status_subscribers')
    with op.batch_alter_table('status_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_incidents_created_at'))
        batch_op.drop_index(batch_op.f('ix_status_incidents_config_id'))
        batch_op.drop_index('idx_config_status')
        batch_op.drop_index('idx_config_created')

    op.drop_table('status_incidents')
    with op.batch_alter_table('status_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_components_config_id'))

    op.drop_table('status_components')
    with op.batch_alter_table('status_page_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_page_configs_website_id'))

    op.drop_table('status_page_configs')
    # ### end Alembic commands ###
