"""Add email confirmation and password reset to User model

Revision ID: ada6a67d00ea
Revises: 77f62e4gc018
Create Date: 2025-11-18 19:21:29.586291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada6a67d00ea'
down_revision = '77f62e4gc018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add security fields to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('email_confirmation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_confirmation_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_password_reset_token', ['password_reset_token'])
        batch_op.create_unique_constraint('uq_users_email_confirmation_token', ['email_confirmation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove security fields from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_password_reset_token', type_='unique')
        batch_op.drop_constraint('uq_users_email_confirmation_token', type_='unique')
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('email_confirmation_sent_at')
        batch_op.drop_column('email_confirmation_token')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
