"""Add email confirmation and password reset to User model

Revision ID: ada6a67d00ea
Revises: 77f62e4gc018
Create Date: 2025-11-18 19:21:29.586291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada6a67d00ea'
down_revision = '77f62e4gc018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_reviews_marketplace_agent'))
        batch_op.drop_index(batch_op.f('ix_agent_reviews_tenant'))
        batch_op.drop_index(batch_op.f('ix_agent_reviews_user'))

    op.drop_table('agent_reviews')
    with op.batch_alter_table('marketplace_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_agents_active'))
        batch_op.drop_index(batch_op.f('ix_marketplace_agents_category'))
        batch_op.drop_index(batch_op.f('ix_marketplace_agents_featured'))
        batch_op.drop_index(batch_op.f('ix_marketplace_agents_published_by'))
        batch_op.drop_index(batch_op.f('ix_marketplace_agents_tenant'))

    op.drop_table('marketplace_agents')
    with op.batch_alter_table('agent_installs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_installs_marketplace_agent'))
        batch_op.drop_index(batch_op.f('ix_agent_installs_tenant'))
        batch_op.drop_index(batch_op.f('ix_agent_installs_user'))

    op.drop_table('agent_installs')
    with op.batch_alter_table('company_enrichment_cache', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_domain'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_confirmation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_confirmation_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['password_reset_token'])
        batch_op.create_unique_constraint(None, ['email_confirmation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('email_confirmation_sent_at')
        batch_op.drop_column('email_confirmation_token')
        batch_op.drop_column('email_confirmed')

    with op.batch_alter_table('company_enrichment_cache', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_domain'), ['domain'], postgresql_nulls_not_distinct=False)

    op.create_table('agent_installs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marketplace_agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_installs_agent_id_fkey')),
    sa.ForeignKeyConstraint(['marketplace_agent_id'], ['marketplace_agents.id'], name=op.f('agent_installs_marketplace_agent_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('agent_installs_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_installs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_installs_pkey'))
    )
    with op.batch_alter_table('agent_installs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_installs_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_installs_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_installs_marketplace_agent'), ['marketplace_agent_id'], unique=False)

    op.create_table('marketplace_agents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('marketplace_agents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('published_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('install_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name='marketplace_agents_published_by_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='marketplace_agents_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='marketplace_agents_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('marketplace_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_agents_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_agents_published_by'), ['published_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_agents_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_agents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_agents_active'), ['is_active'], unique=False)

    op.create_table('agent_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marketplace_agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['marketplace_agent_id'], ['marketplace_agents.id'], name=op.f('agent_reviews_marketplace_agent_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('agent_reviews_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_reviews_pkey'))
    )
    with op.batch_alter_table('agent_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_reviews_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_reviews_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_reviews_marketplace_agent'), ['marketplace_agent_id'], unique=False)

    # ### end Alembic commands ###
