"""Add slug and department_id to channels, mentioned_agent_ids to messages

Revision ID: b5145286969d
Revises: 02a77fb6e90e
Create Date: 2025-11-06 16:33:30.051559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base
import re
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'b5145286969d'
down_revision = '02a77fb6e90e'
branch_labels = None
depends_on = None

Base = declarative_base()

# Temporary model for migration
class Channel(Base):
    __tablename__ = 'channels'
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String(100))
    slug = sa.Column(sa.String(100))
    tenant_id = sa.Column(sa.Integer)
    department_id = sa.Column(sa.Integer)
    is_archived = sa.Column(sa.Boolean, default=False)
    created_by_id = sa.Column(sa.Integer)
    created_at = sa.Column(sa.DateTime)
    updated_at = sa.Column(sa.DateTime)

class Department(Base):
    __tablename__ = 'departments'
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String(100))
    tenant_id = sa.Column(sa.Integer)

def slugify(text):
    """Convert text to URL-friendly slug"""
    text = text.lower()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    text = text.strip('-')
    return text

def upgrade():
    # Add new columns (slug nullable initially)
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_channels_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_slug'), ['slug'], unique=False)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentioned_agent_ids', sa.JSON(), nullable=True))

    # Data migration
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # 1. Populate slug for existing channels
    for channel in session.query(Channel).all():
        if not channel.slug:
            channel.slug = slugify(channel.name)
    session.commit()

    # 2. Auto-create channels for departments
    departments = session.query(Department).all()
    for dept in departments:
        dept_slug = slugify(dept.name)
        # Check if channel already exists for this department
        existing = session.query(Channel).filter_by(
            tenant_id=dept.tenant_id,
            slug=dept_slug
        ).first()

        if not existing:
            # Create new department channel
            now = datetime.utcnow()
            new_channel = Channel(
                name=dept.name,
                slug=dept_slug,
                tenant_id=dept.tenant_id,
                department_id=dept.id,
                is_archived=False,
                created_by_id=None,  # System-created
                created_at=now,
                updated_at=now
            )
            session.add(new_channel)

    session.commit()

    # Make slug NOT NULL after populating
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('mentioned_agent_ids')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_channels_slug'))
        batch_op.drop_index(batch_op.f('ix_channels_department_id'))
        batch_op.drop_column('department_id')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
