"""Add HR models and enable_hr_management flag

Revision ID: baab866886b9
Revises: 5db07fe39c86
Create Date: 2025-12-10 10:38:50.088136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baab866886b9'
down_revision = '5db07fe39c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('bonus_target_percentage', sa.Float(), nullable=True),
    sa.Column('pto_balance', sa.Float(), nullable=True),
    sa.Column('pto_used_this_year', sa.Float(), nullable=True),
    sa.Column('sick_days_balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_number'), ['employee_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=False)

    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_range_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_range_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('application_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('category_scores', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_job_posting_id'), ['job_posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('onboarding_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('buddy_email', sa.String(length=255), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_plans_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_onboarding_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pto_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Float(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('denied_by', sa.String(length=200), nullable=True),
    sa.Column('denied_at', sa.DateTime(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pto_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pto_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('interviewers', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('onboarding_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_email', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_tasks_plan_id'), ['plan_id'], unique=False)

    # Add enable_hr_management column (nullable first for existing data)
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_hr_management', sa.Boolean(), nullable=True))

    # Set default value for existing agents
    op.execute("UPDATE agents SET enable_hr_management = FALSE WHERE enable_hr_management IS NULL")

    # Make column non-nullable
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('enable_hr_management', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('enable_hr_management')

    with op.batch_alter_table('onboarding_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_tasks_plan_id'))

    op.drop_table('onboarding_tasks')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_interviews_candidate_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('pto_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pto_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_status'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_start_date'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_end_date'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_employee_id'))

    op.drop_table('pto_requests')
    with op.batch_alter_table('onboarding_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_plans_employee_id'))

    op.drop_table('onboarding_plans')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_candidates_job_posting_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_job_postings_status'))

    op.drop_table('job_postings')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_employees_status'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_number'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    # ### end Alembic commands ###
