"""add_task_comments_table

Revision ID: c1d81e327972
Revises: 4cd00bb095e0
Create Date: 2025-11-25 13:26:14.767179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d81e327972'
down_revision = '4cd00bb095e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('is_system_generated', sa.Boolean(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_created_at'))

    op.drop_table('task_comments')
    # ### end Alembic commands ###
