"""Add trial tracking fields to users

Revision ID: f7150578d0b5
Revises: d8f4c9e1a2b3
Create Date: 2026-01-08 12:09:51.632945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7150578d0b5'
down_revision = 'd8f4c9e1a2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_user_preferences_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_user_preferences_user_id'))

    op.drop_table('agent_user_preferences')
    with op.batch_alter_table('agent_delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_delegations_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_message_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_orchestrator_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_specialist_id'))

    op.drop_table('agent_delegations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_activated', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trial_activated')
        batch_op.drop_column('trial_end_date')
        batch_op.drop_column('trial_start_date')

    op.create_table('agent_delegations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orchestrator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specialist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delegation_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('agent_delegations_message_id_fkey')),
    sa.ForeignKeyConstraint(['orchestrator_id'], ['agents.id'], name=op.f('agent_delegations_orchestrator_id_fkey')),
    sa.ForeignKeyConstraint(['specialist_id'], ['agents.id'], name=op.f('agent_delegations_specialist_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_delegations_pkey'))
    )
    with op.batch_alter_table('agent_delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_delegations_specialist_id'), ['specialist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_orchestrator_id'), ['orchestrator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_created_at'), ['created_at'], unique=False)

    op.create_table('agent_user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visible_in_sidebar', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('preferred_mode', sa.VARCHAR(length=20), server_default=sa.text("'orchestrator'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_user_preferences_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_user_preferences_pkey')),
    sa.UniqueConstraint('user_id', 'agent_id', name=op.f('unique_user_agent_pref'))
    )
    with op.batch_alter_table('agent_user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_user_preferences_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_user_preferences_agent_id'), ['agent_id'], unique=False)

    # ### end Alembic commands ###
