"""Add lead enrichment tables

Revision ID: f9a2b8c5d3e1
Revises: 7a7f61e75bae
Create Date: 2025-11-18 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a2b8c5d3e1'
down_revision = '7a7f61e75bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### Create CompanyEnrichmentCache table (global cache, not tenant-specific) ###
    op.create_table('company_enrichment_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('company_basics', sa.Text(), nullable=True),  # JSON: industry, size, description, founding_year
    sa.Column('products_services', sa.Text(), nullable=True),  # JSON: what they sell
    sa.Column('competitors', sa.Text(), nullable=True),  # JSON: competitor list
    sa.Column('key_people', sa.Text(), nullable=True),  # JSON: executives, decision makers
    sa.Column('linkedin_company_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('ttl_expires_at', sa.DateTime(), nullable=False),  # Cache expiration (30 days default)
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', name='unique_domain')
    )
    with op.batch_alter_table('company_enrichment_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_enrichment_cache_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_enrichment_cache_ttl_expires_at'), ['ttl_expires_at'], unique=False)

    # ### Add enrichment fields to companies table ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrichment_status', sa.String(length=20), nullable=True))  # 'pending', 'processing', 'completed', 'failed'
        batch_op.add_column(sa.Column('enriched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('enrichment_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lead_score', sa.Integer(), nullable=True))  # 0-100 AI-calculated fit score
        batch_op.add_column(sa.Column('buying_signals', sa.Text(), nullable=True))  # JSON: detected signals (hiring, funding, expansion)
        batch_op.add_column(sa.Column('competitive_position', sa.Text(), nullable=True))  # Market position analysis
        batch_op.add_column(sa.Column('enrichment_summary', sa.Text(), nullable=True))  # AI-generated summary
        batch_op.add_column(sa.Column('enrichment_cache_id', sa.Integer(), nullable=True))  # FK to cache table
        batch_op.create_index(batch_op.f('ix_companies_enrichment_status'), ['enrichment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_lead_score'), ['lead_score'], unique=False)
        batch_op.create_foreign_key('fk_companies_enrichment_cache', 'company_enrichment_cache', ['enrichment_cache_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_enrichment_cache', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_companies_lead_score'))
        batch_op.drop_index(batch_op.f('ix_companies_enrichment_status'))
        batch_op.drop_column('enrichment_cache_id')
        batch_op.drop_column('enrichment_summary')
        batch_op.drop_column('competitive_position')
        batch_op.drop_column('buying_signals')
        batch_op.drop_column('lead_score')
        batch_op.drop_column('enrichment_error')
        batch_op.drop_column('enriched_at')
        batch_op.drop_column('enrichment_status')

    with op.batch_alter_table('company_enrichment_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_enrichment_cache_ttl_expires_at'))
        batch_op.drop_index(batch_op.f('ix_company_enrichment_cache_domain'))

    op.drop_table('company_enrichment_cache')
    # ### end Alembic commands ###
