"""
Generated File Model
Tracks files generated by agents (PDFs, CSVs, Excel files)
"""
from datetime import datetime
from app import db


class GeneratedFile(db.Model):
    """Model for tracking agent-generated files"""
    __tablename__ = 'generated_files'

    id = db.Column(db.Integer, primary_key=True)

    # Ownership and context
    tenant_id = db.Column(db.Integer, db.ForeignKey('tenants.id'), nullable=False, index=True)
    agent_id = db.Column(db.Integer, db.ForeignKey('agents.id'), nullable=True, index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True, index=True)  # User who requested
    message_id = db.Column(db.Integer, db.ForeignKey('messages.id'), nullable=True, index=True)  # Associated message

    # File metadata
    filename = db.Column(db.String(255), nullable=False)
    file_type = db.Column(db.String(50), nullable=False)  # 'pdf', 'csv', 'xlsx'
    mime_type = db.Column(db.String(100), nullable=False)  # MIME type
    file_size = db.Column(db.Integer, nullable=False)  # Size in bytes
    file_purpose = db.Column(db.String(100), nullable=True)  # 'report', 'export', 'invoice', etc.

    # Cloudinary storage
    cloudinary_url = db.Column(db.String(500), nullable=False)
    cloudinary_public_id = db.Column(db.String(255), nullable=False)

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Relationships
    tenant = db.relationship('Tenant', backref=db.backref('generated_files', lazy='dynamic'))
    agent = db.relationship('Agent', backref=db.backref('generated_files', lazy='dynamic'))
    user = db.relationship('User', backref=db.backref('generated_files', lazy='dynamic'))
    message = db.relationship('Message', backref=db.backref('generated_file', uselist=False))

    def __repr__(self):
        return f'<GeneratedFile id={self.id} filename={self.filename}>'

    @property
    def file_size_display(self):
        """Human-readable file size"""
        size = self.file_size
        for unit in ['B', 'KB', 'MB', 'GB']:
            if size < 1024.0:
                return f"{size:.1f} {unit}"
            size /= 1024.0
        return f"{size:.1f} TB"

    @property
    def is_pdf(self):
        """Check if file is a PDF"""
        return self.file_type == 'pdf' or self.mime_type == 'application/pdf'

    @property
    def is_spreadsheet(self):
        """Check if file is a spreadsheet"""
        return self.file_type in ['csv', 'xlsx'] or 'spreadsheet' in self.mime_type

    @property
    def icon_class(self):
        """Get Bootstrap icon class for file type"""
        icon_map = {
            'pdf': 'bi-file-earmark-pdf',
            'csv': 'bi-file-earmark-spreadsheet',
            'xlsx': 'bi-file-earmark-excel',
            'doc': 'bi-file-earmark-word',
            'docx': 'bi-file-earmark-word',
        }
        return icon_map.get(self.file_type, 'bi-file-earmark')

    def to_dict(self):
        """Convert to dictionary for API responses"""
        return {
            'id': self.id,
            'filename': self.filename,
            'file_type': self.file_type,
            'mime_type': self.mime_type,
            'file_size': self.file_size,
            'file_size_display': self.file_size_display,
            'file_purpose': self.file_purpose,
            'cloudinary_url': self.cloudinary_url,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'agent_name': self.agent.name if self.agent else None,
            'user_name': self.user.full_name if self.user else None
        }

    @staticmethod
    def get_workspace_files(tenant_id, limit=100, offset=0):
        """Get all files for a workspace"""
        return GeneratedFile.query.filter_by(
            tenant_id=tenant_id
        ).order_by(
            GeneratedFile.created_at.desc()
        ).limit(limit).offset(offset).all()

    @staticmethod
    def get_user_files(tenant_id, user_id, limit=100, offset=0):
        """Get files requested by a specific user"""
        return GeneratedFile.query.filter_by(
            tenant_id=tenant_id,
            user_id=user_id
        ).order_by(
            GeneratedFile.created_at.desc()
        ).limit(limit).offset(offset).all()

    @staticmethod
    def get_agent_files(agent_id, limit=100, offset=0):
        """Get files generated by a specific agent"""
        return GeneratedFile.query.filter_by(
            agent_id=agent_id
        ).order_by(
            GeneratedFile.created_at.desc()
        ).limit(limit).offset(offset).all()

    @staticmethod
    def count_workspace_files(tenant_id):
        """Count total files in workspace"""
        return GeneratedFile.query.filter_by(tenant_id=tenant_id).count()
